- id: 1
- nombre: Laptop
- categoria: Electrónica
- precio: 1200.00
- fecha_creacion: 2023-01-05
- id: 2
- nombre: Cafetera
- categoria: Hogar
- precio: 80.00
- fecha_creacion: 2023-02-10
- id: 3
- nombre: Bicicleta
- categoria: Deportes
- precio: 300.00
- fecha_creacion: 2023-03-15
